// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type InputCart struct {
	Gameid string `json:"gameid"`
	Userid string `json:"userid"`
}

type InputGame struct {
	Gameid string `json:"gameid"`
	Userid string `json:"userid"`
}

type InputOwnedGame struct {
	Gameid string `json:"gameid"`
	Userid string `json:"userid"`
}

type InputPaymentMethod struct {
	Userid      string    `json:"userid"`
	Card        string    `json:"card"`
	CardNumber  string    `json:"card_number"`
	Date        time.Time `json:"date"`
	Name        string    `json:"name"`
	Address     string    `json:"address"`
	PostalCode  string    `json:"postal_code"`
	PhoneNumber string    `json:"phone_number"`
	Country     string    `json:"country"`
}

type InputReview struct {
	Gameid      string `json:"gameid"`
	Userid      string `json:"userid"`
	Description string `json:"description"`
	Rating      string `json:"rating"`
}

type InputUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Country  string `json:"country"`
}

type InputWishlist struct {
	Gameid string `json:"gameid"`
	Userid string `json:"userid"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateUser struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Country  string  `json:"country"`
	Wallet   float64 `json:"wallet"`
	Image    string  `json:"image"`
}
